name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "KEYSTATIC_GITHUB_CLIENT_ID=${{ secrets.KEYSTATIC_GITHUB_CLIENT_ID }}" > .env
          echo "KEYSTATIC_GITHUB_CLIENT_SECRET=${{ secrets.KEYSTATIC_GITHUB_CLIENT_SECRET }}" >> .env
          echo "KEYSTATIC_SECRET=${{ secrets.KEYSTATIC_SECRET }}" >> .env
          echo "NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG=${{ secrets.NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG }}" >> .env
          echo "GPA=${{ secrets.GPA }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            cd /var/www/threads
            rm -rf .next
            git pull
            pm2 stop instaThreadsDown || true
            pm2 start npm --name instaThreadsDown -- start
