name: DigitalOcean Login and Folder Creation

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: rm node_modules
        run: rm -rf node_modules

      - name: Install Deps
        run: npm i

      - name: Install PM2
        run: npm i -g pm2

      - name: SSH into DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            cd /var/www/threadsdown/
            echo "Folder switched ✅"
            echo "Running PULL ⚠️"
            git pull
            rm -rf node_modules
            rm -rf .next
            npm i
            echo "PULL RAN ✅"
            echo "Adding ENV Variables ⚠️"
            echo "KEYSTATIC_GITHUB_CLIENT_ID=${{ secrets.KEYSTATIC_GITHUB_CLIENT_ID }}" > .env
            echo "KEYSTATIC_GITHUB_CLIENT_SECRET=${{ secrets.KEYSTATIC_GITHUB_CLIENT_SECRET }}" >> .env
            echo "KEYSTATIC_SECRET=${{ secrets.KEYSTATIC_SECRET }}" >> .env
            echo "NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG=${{ secrets.NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG }}" >> .env
            echo "GPA=${{ secrets.GPA }}" >> .env
            echo "Added ENV Variables ✅"
            echo "Deleting .next folder ⚠️"
            rm -rf .next
            echo "Deleted .next folder ✅"
            npm run build
            pm2 delete all
            pm2 start npm --name instaThreadDown -- start
